# USB Ethernet (ECM) gadget.
#
# Usage:
#   usb-gadget up ethernet.toml

name = "ethernet"
# udc = "dummy_udc.0"

[device]
vendor = 0x1209
product = 0x0003
manufacturer = "Example Inc."
product_name = "USB Ethernet"
serial = "0001"

[[config]]
description = "ECM Network"

[[config.function]]
type = "net"
class = "ecm"                 # "ecm", "ecm_subset", "eem", "ncm", or "rndis"
dev_addr = "aa:bb:cc:dd:ee:f0"
host_addr = "aa:bb:cc:dd:ee:f1"
# qmult = 5                   # queue length multiplier
